server:
  port: 9000

housing:
  url: http://ip:port/ServiceRequestPlatform/service/invokeService
spring:
  datasource:
    dynamic:
      primary: kjbbkf
      datasource:
        kjbbkf:
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:mysql://ip:port/zyapi?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=Asia/Shanghai
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: zyapi
          password: *************
          filters: stat
          max-active: 100
          initial-size: 1
          max-wait: 60000
          min-idle: 1
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000
          validation-query: select 1
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          pool-prepared-statements: true
          max-open-prepared-statements: 50
          max-pool-prepared-statement-per-connection-size: 20
  redis:
    database: 0
    timeout: 20000
    password: *******
    lettuce:
      pool:
        #最大连接数(负数表示没有限制)
        max-active: 100
        #最大空闲连接
        max-idle: 10
        #最大阻塞等待时间(负数表示没有限制)
        max-wait: 10000
      cluster:
        refresh:
          adaptive: true
          period: 2500
    cluster:
      nodes:
        - ip:6379
        - ip:6380
        - ip:6379
        - ip:6380
        - ip:6379
        - ip:6380
property:
  file:
    localpath: /data/files/

  url:
    sendNoticeUrl: http://ip:port/estateplat-currenc/rest/v1.0/getNTDyjs
    tokenUrl: http://ip:port/exchange/rest/auth/token
    encryptUrl: http://ip:port/estateplat-olcommon/api/v2/queryModel/encrypt
    bdcfyxxUrl: http://ip:port/exchange/rest/v2/wwsq/bdcfyxx
    dydjUrl: http://ip:port/exchange/rest/v2/yhwwsq/dydj
    dyzxUrl: http://ip:port/exchange/rest/v2/yhwwsq/dyzx
    zzjsUrl: http://ip:port/exchange/rest/v2/yhwwsq/zzjs
    zzwjxzurl: http://ip:port/exchange/rest/v2/yhwwsq/zzwjxz
    tsWwsqFjxxUrl: http://ip:port/exchange/rest/v2/yhwwsq/tsWwsqFjxx
    shebaoUrl:  http://test

aws:
  s3-config:
    end-point: ***.eos.ntyun:8060
    access-key: *******
    secret-key: ************
    bucket: ***